### ISSUE TITLE
Building Docker Image Failed

### ISSUE THREAD

**Issue by glinford** [etopian/docker-koel#1]
Hey, first thanks for the Dockerfile repo :)

I'm having trouble using it, when I try to build the Docker image as follow:
1. git clone https://github.com/etopian/docker-koel.git dockerkoel
2. cd ./dockerkoel
3. vi ./files/.env (I add my admin info and my MySQL info)
4. sudo docker build -t dockerkoel .

And during the building, it ends like this : 

``` shell
Step 16 : RUN su nginx -c "git clone https://github.com/phanan/koel /DATA/htdocs &&    cd /DATA/htdocs &&    npm install &&    composer config github-oauth.github.com  2084a22e9bdb38f94d081ab6f2d5fd339b5292e8 &&    composer install"
 ---> Running in 07c9403be6cf
Cloning into '/DATA/htdocs'...
npm WARN optional dep failed, continuing fsevents@1.0.6
npm WARN optional dep failed, continuing fsevents@1.0.6
npm WARN optional dep failed, continuing fsevents@1.0.6

> expect@1.13.4 postinstall /DATA/htdocs/node_modules/laravel-elixir/node_modules/gulp-phpspec/node_modules/expect
> node ./npm-scripts/postinstall.js

The command '/bin/sh -c su nginx -c "git clone https://github.com/phanan/koel /DATA/htdocs &&    cd /DATA/htdocs &&    npm install &&    composer config github-oauth.github.com  2084a22e9bdb38f94d081ab6f2d5fd339b5292e8 &&    composer install"' returned a non-zero code: 1
```

Sorry If this sounds dummy for you, I'm very new to docker and the PHP Environement.

Cheers,

**Comment by etopian** [comment]
Just pull my image docker pull etopian/docker-koel

you no longer need to edit .env file i think. you can pass everything to Docker when you run the image.

if you still need to do this, then edit the dockerfile and change this line with your own github token
`
composer config github-oauth.github.com  2084a22e9bdb38f94d081ab6f2d5fd339b5292e8
`

you can generate one under settings.
