### ISSUE TITLE
Question : Why this env variables in nginx.conf

### ISSUE THREAD

**Issue by kevincaradant** [etopian/docker-koel#5]
Hi i'm using your repo config for own in arm. I try to build something nice with debian + docker-compose + php-fpm + nginx. So it's not easy but i don't understand why you used this env var because i don't see where you use them. 
Sorry to ask you that , i try to don't fail my bruild on my odroid because it's 3H of time just for one build :/.

```
# run nginx in foreground
daemon off;

error_log /DATA/logs/nginx/nginx-error.log warn;
pid /var/run/nginx.pid;
env DB_HOST;
env DB_NAME;  --> DB_DATABASE ?
env DB_USER;  --> DB_USERNAME ? 
env DB_PASS;  --> DB_PASSWORD ?
```

Thank you :)

Edit : BTW i see that in php-fpm.conf

env["DB_DATABSE"] = "$DB_DATABASE"    , You forgot a "A" for DATABASE ^^. How can it work ?

**Comment by etopian** [comment]
exposes environment vars to PHP through nginx.

**Comment by kevincaradant** [comment]
ok but how you link that ? i put some arrows because for me , if you delete this , it's the same, it's useless  if you don't call this var again ? i don't understand ... sorry ^^. And it's not a problem to forgot the "A" in the env variable in php-fpm.conf file ? your image can't work no ?

**Comment by kevincaradant** [comment]
Hi etopian i get this error 

Do you understand it ? i don't know where can i search. It does not find the mysql database no ? or bad login ? but there are good in the env file and Dokerfile.  In my case i add a docker-compose file where i write all env variables like in Dockerfile  but that didn't change anything :/

Error found it in /DATA/htdocs/storage/logs/laravel.log 

```
[2015-12-24 02:36:11] local.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)' in /DATA/htdocs/vendor/laravel/framework/src/Il$
Stack trace:
#0 /DATA/htdocs/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(55): PDO->__construct('mysql:host=;dbn...', '', '', Array)
#1 /DATA/htdocs/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(22): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=;dbn...', Array, Array)
#2 /DATA/htdocs/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(60): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /
```

**Comment by kevincaradant** [comment]
Hi

I don't use anymore docker-koel, so I close this issue ;). Re open it if you think it's usefull.
